=== guuurris/skolprojektOchLabbar/DM2517 XML For Publicering/src/dtd-xmlschemas/contentmodel.dtd
<!ELEMENT xrecipe (user?, category+, ingredient*)>
<!ELEMENT category (name, food*)>
<!ELEMENT food (name, difficulty, cookingTime, description, procedure, image+, ingredient+, added, portions, portionType)>
<!ELEMENT ingredient (name, quantity?)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT difficulty (#PCDATA)>
<!ELEMENT cookingTime (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT added (#PCDATA)>
<!ELEMENT user EMPTY>
<!ELEMENT portions (#PCDATA)>
<!ELEMENT portionType (#PCDATA)>

<!ATTLIST quantity measureUnit (l|dl|cl|ml|msk|tsk|g|kg|krm|st) #REQUIRED>
<!ATTLIST category position (left|center|right|none) #REQUIRED
				   site (newRecipe|previewRecipe|addCategory|searchRecipe|showRecipe) #IMPLIED>
				   <!--newRecipe anv채nds d책 man skapar nytt recept eller g책r tillbacka fr책n en preview av ett recept -->
<!ATTLIST user id id #REQUIRED>

=== guuurris/skolprojektOchLabbar/DM2517 XML For Publicering/pomodoro/mobile/test.xml
<?xml-stylesheet type="text/xsl" href="mobilegen.xsl" encoding="UTF-8" version="1.0"?>
<!DOCTYPE xrecipe SYSTEM "contentmodel.dtd">
<xrecipe>
	<ingredient> <name>Milk</name> </ingredient> 
	<ingredient> <name>Water</name> </ingredient> 
	<ingredient> <name>Meat</name> </ingredient> 
	<ingredient> <name>Flour</name> </ingredient> 
	<category position="none"> <name>Kött</name> </category> 
	<category position="none"> <name>Fisk</name> </category> 
	<category position="none"> <name>Vegetariskt</name> </category> 
		<category position="none"> <name>aba</name> </category> 
	<category position="none"> <name>sdsds</name> </category> 
	<category position="none"> <name>rgrsgrsg</name> </category> 
		<category position="none"> <name>arheahreh</name> </category> 
	<category position="none"> <name>areharejrtj</name> </category> 
	<category position="none"> <name>gfsjsgfjf</name> </category> 
		<category position="none"> <name>sfgjfgsgdsgfds</name> </category> 
	<category position="none"> <name>sftgkjyghk</name> </category> 
	<category position="none"> <name>asdasds</name> </category> 
	<user id="pnr19850626" loggedin="true"></user>
	<category position="left">
		<name>Kott</name>
		<food>
			<name>Kyckling Tikka Masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har ar en beskrivning av ratten</description>
			<procedure>Har ar proceduren beskriven</procedure>
			<image>images/food1.jpg</image>
			<ingredient>
				<name>Kottbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
		
		<food>
			<name>Basala masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har är en beskrivning av ratten</description>
			<procedure>Har ar proceduren beskriven</procedure>
			<image>images/img4.jpg</image>
			<ingredient>
				<name>Kottbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
	</category>



	<category position="right">
		<name>Kött</name>
	
		<food>
			<name>Basala masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>What the fuck</description>
			<procedure>Har är proceduren beskriven</procedure>
			<image>images/taco-150x150.jpg</image>
			<ingredient>
				<name>Köttbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
				<food>
			<name>Kyckling Tikka Masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har ar en beskrivning av ratten</description>
			<procedure>Har ar proceduren beskriven</procedure>
			<image>images/taco-150x150.jpg</image>
			<ingredient>
				<name>Kottbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
	</category>
	
	<!--sitetestare nedan: fungerande (addRecipe, showRecipe, addCategory, searchRecipe)-->
	<category position="center" site="showRecipe">
		<name>Kott</name>
		<food>
			<name>Centermat är gott</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har är en beskrivning av rätten</description>
			<procedure>Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?</procedure>
			<image>images/food1.jpg</image>
			<ingredient>
				<name>Köttbit</name>
				<quantity measureUnit="st">1.5</quantity>
			</ingredient>
			<ingredient>
				<name>Kalasstek</name>
				<quantity measureUnit="st">2</quantity>
			</ingredient>
			<ingredient>
				<name>Bautastek</name>
				<quantity measureUnit="st">5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
		<food>
			<name>bigfood är äckligt</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har är en beskrivning av rätten</description>
			<procedure>Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?Här är en beskrivning av rätten som du aldrig kommer vilja äta för att du är vegeteriabn din lilla lilla dumma människa! Fattar du inte det!?</procedure>
			<image>images/food1.jpg</image>
			<ingredient>
				<name>Köttbit</name>
				<quantity measureUnit="st">1.5</quantity>
			</ingredient>
			<ingredient>
				<name>Kalasstek</name>
				<quantity measureUnit="st">2</quantity>
			</ingredient>
			<ingredient>
				<name>Bautastek</name>
				<quantity measureUnit="st">5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
		
	</category>

</xrecipe>

=== guuurris/skolprojektOchLabbar/DM2517 XML For Publicering/src/php/xmlGenerator/test.xml
<?xml-stylesheet type="text/xsl" href="generate.xsl" encoding="UTF-8" version="1.0"?>
<!DOCTYPE xrecipe SYSTEM "contentmodel.dtd">
<xrecipe>
	<ingredient> <name>Milk</name> </ingredient> 
	<ingredient> <name>Water</name> </ingredient> 
	<ingredient> <name>Meat</name> </ingredient> 
	<ingredient> <name>Flour</name> </ingredient> 
	<category position="none"> <name>Kött</name> </category> 
	<category position="none"> <name>Fisk</name> </category> 
	<category position="none"> <name>Vegetariskt</name> </category> 
		<category position="none"> <name>aba</name> </category> 
	<category position="none"> <name>sdsds</name> </category> 
	<category position="none"> <name>rgrsgrsg</name> </category> 
		<category position="none"> <name>arheahreh</name> </category> 
	<category position="none"> <name>areharejrtj</name> </category> 
	<category position="none"> <name>gfsjsgfjf</name> </category> 
		<category position="none"> <name>sfgjfgsgdsgfds</name> </category> 
	<category position="none"> <name>sftgkjyghk</name> </category> 
	<category position="none"> <name>asdasds</name> </category> 
	<user id="pnr19850626" loggedin="true"></user>
	<category position="left">
		<name>Kott</name>
		<food>
			<name>Kyckling Tikka Masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har ar en beskrivning av ratten</description>
			<procedure>Har ar proceduren beskriven</procedure>
			<image>images/food1.jpg</image>
			<ingredient>
				<name>Kottbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
		
		<food>
			<name>Basala masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har är en beskrivning av ratten</description>
			<procedure>Har ar proceduren beskriven</procedure>
			<image>images/img4.jpg</image>
			<ingredient>
				<name>Kottbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
	</category>



	<category position="right">
		<name>Kött</name>
	
		<food>
			<name>Basala masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>What the fuck</description>
			<procedure>Har är proceduren beskriven</procedure>
			<image>images/taco-150x150.jpg</image>
			<ingredient>
				<name>Köttbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
				<food>
			<name>Kyckling Tikka Masala</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>Har ar en beskrivning av ratten</description>
			<procedure>Har ar proceduren beskriven</procedure>
			<image>images/taco-150x150.jpg</image>
			<ingredient>
				<name>Kottbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<added>20130101</added>
		</food>
	</category>
	
	<!--sitetestare nedan: fungerande (newRecipe, showRecipe, addCategory, searchRecipe)-->
	<category position="center" site="addCategory">
		<name>Kott</name>
				<food>
			<name>Snyggaste receptet</name>
			<difficulty>3</difficulty>
			<cookingTime>45</cookingTime>
			<description>What the fuck</description>
			<procedure>Har är proceduren beskriven</procedure>
			<image>images/taco-150x150.jpg</image>
			<ingredient>
				<name>Köttbit</name>
				<quantity measureUnit="dl">1.5</quantity>
			</ingredient>
			<portions>4</portions>
			<portionType>port</portionType>
			
			<added>20130101</added>
		</food>




	</category>

</xrecipe>
